export const END_MARKETS = [
  "Construction Tech",
  "Real Estate Tech",
  "FinTech",
  "Payments",
  "InsurTech",
  "HealthTech",
  "HR Tech",
  "Vertical SaaS",
  "Cybersecurity",
  "Data & Analytics",
  "EdTech",
  "Supply Chain / Logistics",
  "Climate Tech",
  "Legal Tech",
  "MarTech / AdTech",
  "Other",
] as const;

export const DEAL_STATUSES = [
  "Saw and Passed",
  "Did Not See",
  "Irrelevant",
] as const;

export const COMPETITOR_FIRMS = [
  "Aldrich Capital Partners",
  "Aquiline",
  "Argentum Group",
  "Arrowroot Capital",
  "Banneker Partners",
  "Battery Ventures (PE)",
  "Blue Heron Capital",
  "Blueprint Equity",
  "BVP Forge",
  "Carrick Capital Partners",
  "Catalyst Investors",
  "Centana Growth Partners",
  "Edison Partners",
  "Elephant",
  "Five Elms Capital",
  "Frontier Growth Partners",
  "Fulcrum Equity Partners",
  "Growth Catalyst Partners",
  "Growth Street Partners",
  "Guidepost Growth Equity",
  "Insight",
  "Integrity Growth Partners",
  "JMI Equity",
  "K1",
  "Kennet Partners (UK / EU)",
  "Lead Edge",
  "LLR Partners",
  "LoneTree Capital",
  "Long Ridge Equity Partners",
  "M33 Growth",
  "Mainsail",
  "Mamba Growth",
  "McCarthy Capital Partners",
  "Nexa Equity",
  "Parker Gale Capital",
  "PeakEquity Partners",
  "PeakSpan Capital",
  "Polaris Growth Fund",
  "Providence Strategic Growth",
  "Radian Capital",
  "Resolve Growth Partners",
  "Resurgens Tech Partners",
  "Riverside Acceleration",
  "Sageview Capital",
  "Serent Capital",
  "Silversmith Capital Partners",
  "SSM Partners",
  "Strattam Capital",
  "Summit Partners",
  "Susquehanna Growth Equity",
  "Updata Partners",
  "Vertica Capital Partners",
  "Vista Endeavor",
  "Volition Capital",
] as const;
