import { Deal } from "./types";

export const SAMPLE_DEALS: Deal[] = [
  // ── February 2026 ──────────────────────────────────────────────
  {
    id: "1",
    date: "2026-02-24",
    company_name: "BuildFlow",
    investor: "Five Elms Capital",
    amount_raised: 45000000,
    end_market: "Construction Tech",
    description: "Cloud-based construction project management platform that streamlines scheduling, budgeting, and subcontractor coordination for mid-market general contractors.",
    source_url: "https://www.businesswire.com/news/home/20260224",
    status: null,
    comments: "",
    created_at: "2026-02-24T14:00:00Z",
    updated_at: "2026-02-24T14:00:00Z",
    deleted_at: null,
  },
  {
    id: "2",
    date: "2026-02-21",
    company_name: "PaymentRails",
    investor: "Lead Edge",
    amount_raised: 80000000,
    end_market: "Payments",
    description: "Embedded B2B payment infrastructure for SaaS platforms, enabling automated invoicing, reconciliation, and cross-border payouts.",
    source_url: "https://techcrunch.com/2026/02/21/paymentrails",
    status: "Saw and Passed",
    comments: "Looked at this last year. Valuation was too high for our taste.",
    created_at: "2026-02-21T09:30:00Z",
    updated_at: "2026-02-21T15:00:00Z",
    deleted_at: null,
  },
  {
    id: "3",
    date: "2026-02-20",
    company_name: "CyberShield AI",
    investor: "Silversmith Capital Partners",
    amount_raised: 60000000,
    end_market: "Cybersecurity",
    description: "ML-powered insider threat detection and response platform targeting mid-market enterprises with 500-5,000 employees.",
    source_url: "https://www.prnewswire.com/news-releases/20260220",
    status: "Did Not See",
    comments: "",
    created_at: "2026-02-20T11:00:00Z",
    updated_at: "2026-02-20T11:00:00Z",
    deleted_at: null,
  },
  {
    id: "4",
    date: "2026-02-19",
    company_name: "InsureFlow",
    investor: "JMI Equity",
    amount_raised: null,
    end_market: "InsurTech",
    description: "Automates commercial insurance underwriting workflows for specialty lines, reducing quote turnaround from days to minutes.",
    source_url: "https://www.axios.com/pro/deals/20260219",
    status: null,
    comments: "",
    created_at: "2026-02-19T08:00:00Z",
    updated_at: "2026-02-19T08:00:00Z",
    deleted_at: null,
  },
  {
    id: "5",
    date: "2026-02-18",
    company_name: "DocketAI",
    investor: "LLR Partners",
    amount_raised: 52000000,
    end_market: "Legal Tech",
    description: "AI-powered contract lifecycle management platform for corporate legal teams. Automates review, redlining, and obligation tracking across enterprise agreements.",
    source_url: "https://www.pehub.com/2026/02/docketai",
    status: null,
    comments: "Interesting space. Worth a closer look at their competitive positioning vs. Ironclad.",
    created_at: "2026-02-18T09:00:00Z",
    updated_at: "2026-02-18T14:00:00Z",
    deleted_at: null,
  },
  {
    id: "6",
    date: "2026-02-14",
    company_name: "ClimaTrack",
    investor: "Summit Partners",
    amount_raised: 35000000,
    end_market: "Climate Tech",
    description: "Carbon accounting and ESG reporting software for mid-market manufacturing companies, integrating directly with ERP systems.",
    source_url: "https://www.pehub.com/2026/02/climatrack",
    status: "Irrelevant",
    comments: "Too early stage for us — Series A, not growth equity.",
    created_at: "2026-02-14T10:00:00Z",
    updated_at: "2026-02-15T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "7",
    date: "2026-02-13",
    company_name: "FreightMind",
    investor: "Mainsail",
    amount_raised: 72000000,
    end_market: "Supply Chain / Logistics",
    description: "AI-driven freight brokerage platform that automates carrier matching, rate negotiation, and shipment tracking for mid-market shippers.",
    source_url: "https://www.businesswire.com/news/home/20260213",
    status: "Saw and Passed",
    comments: "Competitive market. Already looked at 3 similar companies in H2 2025.",
    created_at: "2026-02-13T09:00:00Z",
    updated_at: "2026-02-13T16:00:00Z",
    deleted_at: null,
  },
  {
    id: "8",
    date: "2026-02-12",
    company_name: "Appraisal.io",
    investor: "Centana Growth Partners",
    amount_raised: 40000000,
    end_market: "Real Estate Tech",
    description: "Automated commercial real estate appraisal platform using computer vision and comparable sales data. Reduces appraisal turnaround from weeks to hours.",
    source_url: "https://techcrunch.com/2026/02/12/appraisalio",
    status: null,
    comments: "",
    created_at: "2026-02-12T10:00:00Z",
    updated_at: "2026-02-12T10:00:00Z",
    deleted_at: null,
  },
  {
    id: "9",
    date: "2026-02-10",
    company_name: "TalentOS",
    investor: "Edison Partners",
    amount_raised: 55000000,
    end_market: "HR Tech",
    description: "Unified talent management suite for mid-market companies. Combines ATS, onboarding, performance reviews, and compensation benchmarking in one platform.",
    source_url: "https://www.prnewswire.com/news-releases/20260210",
    status: "Did Not See",
    comments: "Missed this one. Edison moved fast.",
    created_at: "2026-02-10T09:00:00Z",
    updated_at: "2026-02-11T10:00:00Z",
    deleted_at: null,
  },
  {
    id: "10",
    date: "2026-02-07",
    company_name: "Plumb",
    investor: "Updata Partners",
    amount_raised: 90000000,
    end_market: "Vertical SaaS",
    description: "All-in-one operating system for residential plumbing and HVAC contractors. Handles dispatching, invoicing, inventory, and customer CRM.",
    source_url: "https://www.axios.com/pro/deals/20260207",
    status: "Saw and Passed",
    comments: "Good business but we thought the TAM ceiling was too low for our target return profile.",
    created_at: "2026-02-07T09:00:00Z",
    updated_at: "2026-02-08T11:00:00Z",
    deleted_at: null,
  },
  {
    id: "11",
    date: "2026-02-06",
    company_name: "AdSight",
    investor: "PeakSpan Capital",
    amount_raised: 38000000,
    end_market: "MarTech / AdTech",
    description: "Privacy-first marketing attribution platform that helps DTC and e-commerce brands measure campaign ROI without relying on third-party cookies.",
    source_url: "https://www.businesswire.com/news/home/20260206",
    status: null,
    comments: "",
    created_at: "2026-02-06T09:00:00Z",
    updated_at: "2026-02-06T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "12",
    date: "2026-02-04",
    company_name: "Vaultik",
    investor: "K1",
    amount_raised: 120000000,
    end_market: "Cybersecurity",
    description: "Enterprise secrets management and zero-trust access platform. Centralizes API keys, credentials, and certificates across hybrid cloud environments.",
    source_url: "https://techcrunch.com/2026/02/04/vaultik",
    status: "Did Not See",
    comments: "K1 has been very active in cyber. Third deal in 6 months.",
    created_at: "2026-02-04T09:00:00Z",
    updated_at: "2026-02-05T08:00:00Z",
    deleted_at: null,
  },
  // ── January 2026 ──────────────────────────────────────────────
  {
    id: "13",
    date: "2026-01-30",
    company_name: "Strata Benefits",
    investor: "Catalyst Investors",
    amount_raised: 65000000,
    end_market: "InsurTech",
    description: "Benefits administration platform for mid-market employers. Streamlines enrollment, compliance, and broker management for companies with 200-2,000 employees.",
    source_url: "https://www.pehub.com/2026/01/strata-benefits",
    status: "Saw and Passed",
    comments: "We were in the process on this. Lost to Catalyst on price — they paid 14x ARR.",
    created_at: "2026-01-30T09:00:00Z",
    updated_at: "2026-01-31T14:00:00Z",
    deleted_at: null,
  },
  {
    id: "14",
    date: "2026-01-28",
    company_name: "Fieldwork",
    investor: "Serent Capital",
    amount_raised: 48000000,
    end_market: "Construction Tech",
    description: "Mobile-first field service management for specialty subcontractors. Handles time tracking, daily logs, safety compliance, and change order management.",
    source_url: "https://www.businesswire.com/news/home/20260128",
    status: null,
    comments: "Similar to BuildOps. Need to understand differentiation.",
    created_at: "2026-01-28T09:00:00Z",
    updated_at: "2026-01-28T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "15",
    date: "2026-01-27",
    company_name: "Ledgr",
    investor: "Volition Capital",
    amount_raised: 30000000,
    end_market: "FinTech",
    description: "Automated bookkeeping and financial close platform for SMB accounting firms. Uses AI to categorize transactions and reconcile accounts.",
    source_url: "https://www.axios.com/pro/deals/20260127",
    status: null,
    comments: "",
    created_at: "2026-01-27T09:00:00Z",
    updated_at: "2026-01-27T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "16",
    date: "2026-01-23",
    company_name: "SchoolRunner",
    investor: "Susquehanna Growth Equity",
    amount_raised: 42000000,
    end_market: "EdTech",
    description: "K-12 school operations platform combining SIS, behavior tracking, communication, and analytics. Serves charter networks and mid-size districts.",
    source_url: "https://www.prnewswire.com/news-releases/20260123",
    status: "Irrelevant",
    comments: "EdTech is outside our core focus areas.",
    created_at: "2026-01-23T09:00:00Z",
    updated_at: "2026-01-24T10:00:00Z",
    deleted_at: null,
  },
  {
    id: "17",
    date: "2026-01-22",
    company_name: "Canopy Analytics",
    investor: "Providence Strategic Growth",
    amount_raised: 75000000,
    end_market: "Data & Analytics",
    description: "Customer data platform for B2B SaaS companies. Unifies product usage, billing, and support data to predict churn and identify expansion opportunities.",
    source_url: "https://techcrunch.com/2026/01/22/canopy-analytics",
    status: "Saw and Passed",
    comments: "Strong product but concentration risk — top 5 customers are 40% of ARR.",
    created_at: "2026-01-22T09:00:00Z",
    updated_at: "2026-01-23T11:00:00Z",
    deleted_at: null,
  },
  {
    id: "18",
    date: "2026-01-20",
    company_name: "Gradeient",
    investor: "Insight",
    amount_raised: 200000000,
    end_market: "Data & Analytics",
    description: "Enterprise AI model monitoring and observability platform. Tracks model drift, fairness metrics, and inference costs across production ML pipelines.",
    source_url: "https://www.businesswire.com/news/home/20260120",
    status: "Did Not See",
    comments: "Massive round from Insight. This is Series D territory.",
    created_at: "2026-01-20T09:00:00Z",
    updated_at: "2026-01-21T08:00:00Z",
    deleted_at: null,
  },
  {
    id: "19",
    date: "2026-01-17",
    company_name: "ClearClaim",
    investor: "Carrick Capital Partners",
    amount_raised: 58000000,
    end_market: "HealthTech",
    description: "Revenue cycle management platform for specialty physician practices. Automates claim submission, denial management, and payer contract optimization.",
    source_url: "https://www.pehub.com/2026/01/clearclaim",
    status: null,
    comments: "Healthcare RCM is interesting. Should we take a deeper look at the space?",
    created_at: "2026-01-17T09:00:00Z",
    updated_at: "2026-01-17T15:00:00Z",
    deleted_at: null,
  },
  {
    id: "20",
    date: "2026-01-15",
    company_name: "TrussPoint",
    investor: "Battery Ventures (PE)",
    amount_raised: 95000000,
    end_market: "Cybersecurity",
    description: "Cloud security posture management (CSPM) platform with automated remediation. Helps enterprises maintain compliance across AWS, Azure, and GCP.",
    source_url: "https://techcrunch.com/2026/01/15/trusspoint",
    status: "Did Not See",
    comments: "",
    created_at: "2026-01-15T09:00:00Z",
    updated_at: "2026-01-15T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "21",
    date: "2026-01-14",
    company_name: "Rellium",
    investor: "Elephant",
    amount_raised: 33000000,
    end_market: "FinTech",
    description: "Embedded lending infrastructure for vertical SaaS platforms. Enables software companies to offer working capital loans to their SMB customers.",
    source_url: "https://www.axios.com/pro/deals/20260114",
    status: null,
    comments: "",
    created_at: "2026-01-14T09:00:00Z",
    updated_at: "2026-01-14T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "22",
    date: "2026-01-13",
    company_name: "ParkVue",
    investor: "Frontier Growth Partners",
    amount_raised: 28000000,
    end_market: "Real Estate Tech",
    description: "Smart parking management platform for commercial real estate owners. Combines IoT sensors, dynamic pricing, and tenant billing for parking assets.",
    source_url: "https://www.businesswire.com/news/home/20260113",
    status: "Irrelevant",
    comments: "Hardware-heavy business. Not a fit for our software-only mandate.",
    created_at: "2026-01-13T09:00:00Z",
    updated_at: "2026-01-14T08:00:00Z",
    deleted_at: null,
  },
  {
    id: "23",
    date: "2026-01-10",
    company_name: "DispatchIQ",
    investor: "Riverside Acceleration",
    amount_raised: null,
    end_market: "Supply Chain / Logistics",
    description: "Last-mile delivery optimization software for regional parcel carriers and 3PLs. Uses route AI to reduce delivery costs by 15-25%.",
    source_url: "https://www.prnewswire.com/news-releases/20260110",
    status: null,
    comments: "",
    created_at: "2026-01-10T09:00:00Z",
    updated_at: "2026-01-10T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "24",
    date: "2026-01-09",
    company_name: "ComplianceHQ",
    investor: "M33 Growth",
    amount_raised: 50000000,
    end_market: "FinTech",
    description: "Regulatory compliance automation for community banks and credit unions. Monitors regulatory changes and auto-updates policies, procedures, and audit trails.",
    source_url: "https://www.pehub.com/2026/01/compliancehq",
    status: "Saw and Passed",
    comments: "Solid business but regulatory risk if banking rules change. Passed at 11x ARR.",
    created_at: "2026-01-09T09:00:00Z",
    updated_at: "2026-01-10T14:00:00Z",
    deleted_at: null,
  },
  {
    id: "25",
    date: "2026-01-08",
    company_name: "AireSpring Health",
    investor: "Resolve Growth Partners",
    amount_raised: 44000000,
    end_market: "HealthTech",
    description: "Patient engagement and virtual care coordination platform for large multi-location physician groups. Integrates with major EHR systems.",
    source_url: "https://www.businesswire.com/news/home/20260108",
    status: null,
    comments: "Heard good things from our LP network. Strong NRR above 130%.",
    created_at: "2026-01-08T09:00:00Z",
    updated_at: "2026-01-09T10:00:00Z",
    deleted_at: null,
  },
  {
    id: "26",
    date: "2026-01-07",
    company_name: "Propel Payments",
    investor: "Sageview Capital",
    amount_raised: 110000000,
    end_market: "Payments",
    description: "Integrated payments platform for franchise and multi-location restaurant brands. Bundles POS processing, payroll cards, and tip management.",
    source_url: "https://techcrunch.com/2026/01/07/propel-payments",
    status: "Saw and Passed",
    comments: "Evaluated in Q4 2025. Passed due to merchant concentration risk and thin margins.",
    created_at: "2026-01-07T09:00:00Z",
    updated_at: "2026-01-08T11:00:00Z",
    deleted_at: null,
  },
  {
    id: "27",
    date: "2026-01-06",
    company_name: "Mosaic Learning",
    investor: "Strattam Capital",
    amount_raised: 25000000,
    end_market: "EdTech",
    description: "Corporate L&D platform that uses adaptive learning paths and skills mapping to upskill enterprise workforces. Focused on technical and compliance training.",
    source_url: "https://www.prnewswire.com/news-releases/20260106",
    status: "Irrelevant",
    comments: "Corporate L&D market is crowded. Too many incumbents.",
    created_at: "2026-01-06T09:00:00Z",
    updated_at: "2026-01-07T08:00:00Z",
    deleted_at: null,
  },
  {
    id: "28",
    date: "2026-01-05",
    company_name: "PermitFlow",
    investor: "Arrowroot Capital",
    amount_raised: 37000000,
    end_market: "Construction Tech",
    description: "Software platform that automates the building permit application process. Digitizes submissions, tracks approvals, and integrates with municipal AHJ systems.",
    source_url: "https://www.axios.com/pro/deals/20260105",
    status: null,
    comments: "Love the thesis here. Permitting is a massive pain point. Should we reach out to management?",
    created_at: "2026-01-05T09:00:00Z",
    updated_at: "2026-01-06T16:00:00Z",
    deleted_at: null,
  },
  {
    id: "29",
    date: "2026-01-03",
    company_name: "VaultKey",
    investor: "Long Ridge Equity Partners",
    amount_raised: 68000000,
    end_market: "FinTech",
    description: "Digital asset custody and treasury management platform for institutional investors. SOC 2 Type II certified with insurance-backed cold storage.",
    source_url: "https://www.businesswire.com/news/home/20260103",
    status: "Did Not See",
    comments: "",
    created_at: "2026-01-03T09:00:00Z",
    updated_at: "2026-01-03T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "30",
    date: "2026-01-02",
    company_name: "GridSync",
    investor: "Banneker Partners",
    amount_raised: 41000000,
    end_market: "Climate Tech",
    description: "Software for electric utilities to manage distributed energy resources (DERs). Optimizes solar, battery, and EV charging across the grid in real time.",
    source_url: "https://techcrunch.com/2026/01/02/gridsync",
    status: null,
    comments: "",
    created_at: "2026-01-02T09:00:00Z",
    updated_at: "2026-01-02T09:00:00Z",
    deleted_at: null,
  },
];
