import { Deal } from "./types";

export const SAMPLE_DEALS: Deal[] = [
  // ── February 2026 ──────────────────────────────────────────────
  {
    id: "d01",
    date: "2026-02-20",
    company_name: "Pepper",
    investor: "Lead Edge",
    amount_raised: 50000000,
    end_market: "Supply Chain / Logistics",
    description: "Suite of products helping independent food distributors modernize core workflows across ordering, sales and marketing, accounts receivable, and embedded payments. Serves 500+ distributors representing ~$30B in annual GMV.",
    source_url: "https://retailtechinnovationhub.com/home/2026/2/22/lead-edge-capital-heads-up-50-million-series-c-funding-round-for-food-distribution-specialist-pepper",
    status: null,
    comments: "",
    created_at: "2026-02-20T14:00:00Z",
    updated_at: "2026-02-20T14:00:00Z",
    deleted_at: null,
  },
  {
    id: "d02",
    date: "2026-02-19",
    company_name: "Jump",
    investor: "Insight",
    amount_raised: 80000000,
    end_market: "FinTech",
    description: "AI-native operating system for financial advisors. Scaled from launch to 27,000 advisors in under two years; nearly one in ten US financial advisors now use the platform.",
    source_url: "https://www.businesswire.com/news/home/20260219487440/en/Jump-Raises-$80-Million-Series-B-Led-by-Insight-Partners-to-Expand-AI-Operating-System-for-Financial-Advisors",
    status: null,
    comments: "",
    created_at: "2026-02-19T09:00:00Z",
    updated_at: "2026-02-19T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "d03",
    date: "2026-02-18",
    company_name: "Payra",
    investor: "Edison Partners",
    amount_raised: 15000000,
    end_market: "FinTech",
    description: "B2B payments and accounts receivable automation platform built for blue-collar and construction-oriented businesses running on legacy ERP systems. Modernizes cash collection without replacing existing ERPs.",
    source_url: "https://www.businesswire.com/news/home/20260218544563/en/Payra-and-Edison-Partners-Announce-$15M-Growth-Investment-to-Modernize-Accounts-Receivable-for-Americas-Heartland-Businesses",
    status: null,
    comments: "",
    created_at: "2026-02-18T13:00:00Z",
    updated_at: "2026-02-18T13:00:00Z",
    deleted_at: null,
  },
  {
    id: "d04",
    date: "2026-02-18",
    company_name: "Kombo",
    investor: "Volition Capital",
    amount_raised: 25000000,
    end_market: "HR Tech",
    description: "Unified API infrastructure platform for HR integrations, solving one of the most critical challenges in the global HR technology market. Enables software companies to connect to hundreds of HR systems through a single API.",
    source_url: "https://www.volitioncapital.com/portfolio/",
    status: null,
    comments: "",
    created_at: "2026-02-18T09:00:00Z",
    updated_at: "2026-02-18T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "d05",
    date: "2026-02-17",
    company_name: "Dataro",
    investor: "Blueprint Equity",
    amount_raised: 14280000,
    end_market: "Data & Analytics",
    description: "AI-driven fundraising intelligence platform for charities and nonprofits. Converts donor data into predictive insights and guided actions, serving 300+ organizations including World Central Kitchen and Amnesty International.",
    source_url: "https://www.prnewswire.com/news-releases/dataro-raises-14-28m-series-a-to-power-ai-native-fundraising-for-charities-302688752.html",
    status: null,
    comments: "",
    created_at: "2026-02-17T14:00:00Z",
    updated_at: "2026-02-17T14:00:00Z",
    deleted_at: null,
  },
  {
    id: "d06",
    date: "2026-02-12",
    company_name: "Lennections",
    investor: "Serent Capital",
    amount_raised: null,
    end_market: "EdTech",
    description: "Educational technology and training services platform. Investment amount undisclosed.",
    source_url: "https://serentcapital.com/portfolio/",
    status: null,
    comments: "",
    created_at: "2026-02-12T09:00:00Z",
    updated_at: "2026-02-12T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "d07",
    date: "2026-02-10",
    company_name: "Hauler Hero",
    investor: "Frontier Growth Partners",
    amount_raised: 16000000,
    end_market: "Vertical SaaS",
    description: "All-in-one AI-powered software platform for waste management companies covering CRM, billing, routing, and operations. Serves 200+ waste management companies from independent haulers to major municipalities.",
    source_url: "https://techcrunch.com/2026/02/10/hauler-hero-collects-16m-for-its-ai-waste-management-software/",
    status: null,
    comments: "",
    created_at: "2026-02-10T15:00:00Z",
    updated_at: "2026-02-10T15:00:00Z",
    deleted_at: null,
  },
  {
    id: "d08",
    date: "2026-02-03",
    company_name: "Acterys",
    investor: "JMI Equity",
    amount_raised: null,
    end_market: "Data & Analytics",
    description: "Cloud-based FP&A and analytics platform that extends Microsoft Power BI and Excel with writeback, planning, and consolidation capabilities for finance teams. Co-invested with Centana Growth Partners.",
    source_url: "https://www.jmi.com/companies/",
    status: null,
    comments: "",
    created_at: "2026-02-03T09:00:00Z",
    updated_at: "2026-02-03T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "d09",
    date: "2026-02-03",
    company_name: "Pasito",
    investor: "Insight",
    amount_raised: 21000000,
    end_market: "HR Tech",
    description: "AI-native workspace for the benefits industry, covering group health, life, and retirement benefits. Uses AI to automate and streamline benefits administration workflows.",
    source_url: "https://www.prnewswire.com/news-releases/pasito-raises-21-million-series-a-led-by-insight-partners-to-build-ai-workspace-for-the-benefits-industry-302675272.html",
    status: null,
    comments: "",
    created_at: "2026-02-03T09:00:00Z",
    updated_at: "2026-02-03T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "d10",
    date: "2026-02-02",
    company_name: "CyberFOX",
    investor: "Radian Capital",
    amount_raised: null,
    end_market: "Cybersecurity",
    description: "Next-generation cybersecurity platform for managed service providers (MSPs) that enhances and tightens security practices while simplifying end-user experiences. Nine-figure round led by Level Equity with Radian Capital participation. First external capital raise.",
    source_url: "https://www.globenewswire.com/news-release/2026/02/02/3230331/0/en/CyberFOX-Raises-Significant-Growth-Financing-to-Accelerate-its-Next-Generation-Cybersecurity-Platform.html",
    status: null,
    comments: "",
    created_at: "2026-02-02T09:00:00Z",
    updated_at: "2026-02-02T09:00:00Z",
    deleted_at: null,
  },
  // ── January 2026 ──────────────────────────────────────────────
  {
    id: "d11",
    date: "2026-01-30",
    company_name: "Apploi",
    investor: "LLR Partners",
    amount_raised: null,
    end_market: "HR Tech",
    description: "Healthcare hiring and onboarding platform with tools for credential collection, monitoring, and compliance management for nurses and caregivers.",
    source_url: "https://apploi.com/press/apploi-raises-25m-for-healthcare-hiring/",
    status: null,
    comments: "",
    created_at: "2026-01-30T09:00:00Z",
    updated_at: "2026-01-30T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "d12",
    date: "2026-01-27",
    company_name: "Summize",
    investor: "Kennet Partners (UK / EU)",
    amount_raised: 50000000,
    end_market: "Legal Tech",
    description: "AI-powered contract lifecycle management (CLM) software. Five consecutive years of 100%+ ARR growth; customer bookings grew 92% and ARR increased 97% YoY in H2 2025.",
    source_url: "https://www.businesswire.com/news/home/20260127240240/en/Summize-Raises-$50-Million-to-Accelerate-Global-Expansion-and-Advance-AI-Contract-Intelligence",
    status: null,
    comments: "",
    created_at: "2026-01-27T09:00:00Z",
    updated_at: "2026-01-27T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "d13",
    date: "2026-01-26",
    company_name: "Ressio Software",
    investor: "Blueprint Equity",
    amount_raised: 8750000,
    end_market: "Construction Tech",
    description: "AI-powered construction management platform purpose-built for residential home builders and remodelers. Helps construction leaders manage schedules, budgets, documents, and stakeholder collaboration.",
    source_url: "https://finance.yahoo.com/news/ressio-software-raises-series-led-140000044.html",
    status: null,
    comments: "",
    created_at: "2026-01-26T14:00:00Z",
    updated_at: "2026-01-26T14:00:00Z",
    deleted_at: null,
  },
  {
    id: "d14",
    date: "2026-01-21",
    company_name: "Benepass",
    investor: "Centana Growth Partners",
    amount_raised: 40000000,
    end_market: "HR Tech",
    description: "Global benefits capital management platform helping employers redesign benefits for rising healthcare costs. Powered by a proprietary financial ledger, serves 250+ employers and has processed 4.5M+ card transactions managing $900M+ in benefits funding.",
    source_url: "https://www.prnewswire.com/news-releases/benepass-raises-40m-series-b-to-help-employers-redesign-benefits-for-rising-healthcare-costs-302666704.html",
    status: null,
    comments: "",
    created_at: "2026-01-21T14:00:00Z",
    updated_at: "2026-01-21T14:00:00Z",
    deleted_at: null,
  },
  {
    id: "d15",
    date: "2026-01-21",
    company_name: "OrgChart",
    investor: "Resurgens Tech Partners",
    amount_raised: null,
    end_market: "HR Tech",
    description: "Leading organizational chart and workforce planning solution. Resurgens became the primary investor; Lock 8 Partners remained as minority partner.",
    source_url: "https://www.businesswire.com/news/home/20260121357766/en/OrgChart-Partners-with-Resurgens-Technology-to-Fuel-Next-Phase-of-Growth",
    status: null,
    comments: "",
    created_at: "2026-01-21T09:00:00Z",
    updated_at: "2026-01-21T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "d16",
    date: "2026-01-20",
    company_name: "SpryPoint",
    investor: "Insight",
    amount_raised: null,
    end_market: "Vertical SaaS",
    description: "Cloud-native customer service and operations platform for utilities. Strategic growth investment to accelerate product development, drive customer time-to-value, and scale the organization.",
    source_url: "https://www.insightpartners.com/ideas/sprypoint-secures-strategic-growth-investment-from-insight-partners/",
    status: null,
    comments: "",
    created_at: "2026-01-20T09:00:00Z",
    updated_at: "2026-01-20T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "d17",
    date: "2026-01-20",
    company_name: "TitanX",
    investor: "Updata Partners",
    amount_raised: 27000000,
    end_market: "Data & Analytics",
    description: "Data and software intelligence platform that enables outbound sales teams to predict which prospects will answer the phone. Pioneering the Phone Intent category for precision outbound sales.",
    source_url: "https://www.prnewswire.com/news-releases/titanx-raises-27-million-series-a-to-scale-the-phone-intent-category-302664752.html",
    status: null,
    comments: "",
    created_at: "2026-01-20T13:43:00Z",
    updated_at: "2026-01-20T13:43:00Z",
    deleted_at: null,
  },
  {
    id: "d18",
    date: "2026-01-14",
    company_name: "MontyCloud",
    investor: "Riverside Acceleration",
    amount_raised: 11500000,
    end_market: "Data & Analytics",
    description: "Autonomous cloud operations platform that helps companies run and control cloud infrastructure automatically, from enforcing governance policies to optimizing cloud spend across multicloud environments.",
    source_url: "https://www.geekwire.com/2026/seattle-area-startup-montycloud-raises-series-b-round-to-boost-cloud-operations-software/",
    status: null,
    comments: "",
    created_at: "2026-01-14T09:00:00Z",
    updated_at: "2026-01-14T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "d19",
    date: "2026-01-12",
    company_name: "Trybe",
    investor: "Five Elms Capital",
    amount_raised: 30000000,
    end_market: "Vertical SaaS",
    description: "Leading provider of spa, bathhouse, leisure, and activity management software. Investment will enable global expansion, AI-powered workflows to enhance guest experiences, and next-generation platform development.",
    source_url: "https://www.prnewswire.com/news-releases/trybe-announces-30m-series-a-investment-from-five-elms-capital-302658132.html",
    status: null,
    comments: "",
    created_at: "2026-01-12T09:00:00Z",
    updated_at: "2026-01-12T09:00:00Z",
    deleted_at: null,
  },
  {
    id: "d20",
    date: "2026-01-07",
    company_name: "Biller Genie",
    investor: "Radian Capital",
    amount_raised: 22000000,
    end_market: "FinTech",
    description: "Cloud-based accounts receivable automation platform that automates invoicing, payment collection, follow-up, and reconciliation. Integrates with leading accounting software and payment providers. Revenue grew at 126% CAGR since 2020 commercial launch.",
    source_url: "https://billergenie.com/biller-genie-raises-22-million-series-b-led-by-radian-capital/",
    status: null,
    comments: "",
    created_at: "2026-01-07T09:00:00Z",
    updated_at: "2026-01-07T09:00:00Z",
    deleted_at: null,
  },
];
